# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('sexo', models.TextField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='articulos',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='prueba.usuarios'),
        ),
    ]
