# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0006_auto_20160111_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulos',
            name='usuario',
        ),
    ]
