# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0007_remove_articulos_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='articulos',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='usuario',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='sexo',
            field=models.CharField(max_length=1),
        ),
    ]
